description: |
  The Debian-based Docker container to use when
  installing/configuring the AWS CLI

parameters:
  python-version:
    type: string
    default: "2.7"

  debian-release:
    type: string
    default: "stretch"

docker:
  - image: circleci/python:<<parameters.python-version>>-<<parameters.debian-release>>
