description: Configure a new profile to assume a role defined by a role_arn.
usage:
  version: 2.1

  orbs:
    aws-cli: circleci/aws-cli@4.0

  jobs:
    configure_role_arn:
      executor: aws-cli/default
      steps:
        - checkout
        - aws-cli/setup: #  Required: Run setup command first to configure credentials for source profile
            profile_name: default
        - aws-cli/role_arn_setup:
            profile_name: new-profile
            role_arn: "arn:aws:iam::123456789012:role/example-role"
            source_profile: default # Use profile created from setup command
        - run: aws sts assume-role --role_arn "arn:aws:iam::123456789012:role/example-role" --role_session_name AWSCLI-Session

  workflows:
    aws-cli:
      jobs:
        - configure_role_arn
