description: Configure a new profile to assume a role defined by a role-arn.
usage:
  version: 2.1

  orbs:
    aws-cli: circleci/aws-cli@2.0

  jobs:
    configure-role-arn:
      executor: aws-cli/default
      steps:
        - checkout
        - aws-cli/setup: #  Rquired: Run setup command first to configure credentials for source profile 
            profile-name: default
        - aws-cli/role-arn-setup:
            profile-name: new-profile
            role-arn: "arn:aws:iam::0123456789:role/foo-bar"
            source-profile: default # Use profile created from setup command
        - run: echo "Run your code here"

  workflows:
    aws-cli:
      jobs:
        -  configure-role-arn
