version: 2.1
orbs:
  aws-cli: circleci/aws-cli@0.1.20

jobs:
  aws-cli-example:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          aws-access-key-id: AWS_ACCESS_KEY_ID_BLUE
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY_BLUE
          aws-region: AWS_REGION_BLUE
      - run: echo "Run your code here"
workflows:
  version: 2
  aws-cli:
    jobs:
      - aws-cli-example:
          context: aws
